crossroads/shared.goodcity

- app/routes/application.js
- app/utils/logger.js
https://errbit.crossroads.org.hk/apps/54bdf432657272e25e010000/problems/551bc7d665727287690d0000
> Gcw 97 errbit errors display username to errbit trace

- addon/initializers/i18n-en.coffee
- addon/initializers/i18n-zh-tw.coffee
- app/components/donor-conditions.js
- app/controllers/item/edit_images.js
- app/models/rejection_reason.js
- app/styles/templates/item/_edit.scss
- app/templates/components/donor-conditions.hbs
- app/templates/item/item_edit_form.hbs
This PR is dependent on https://github.com/crossroads/shared.goodcity/pull/54.
Please merge https://github.com/crossroads/shared.goodcity/pull/54 before merging this PR.
Thanks.
> GCW-379 Admin can set / edit donor description and item condition

- app/models/offer.js
- app/styles/_custom.scss
- app/styles/templates/offer/_status_message.scss
- add style for confirm-receiving-overlay
- 'isReceiving' property for offer
- receiving detail attributes for offer
- update style for receiving offer
- updare receiving offer's state to display on offers-page
> GCW 629 receiving state for offer

- app/components/numeric-input.js
Admin accept package component sent number values and numeric-input component was breaking. So - - fix it by supporting number values
- Earlier component was using fixed length 8 now made it pattern based, it will validate based on the pattern.
> Improved numeric-input component to support number value

- app/utils/records.js
on Error throw the response to the app
> GCW-574 Added try-catch block back 

- app/services/cordova.js
https://jira.crossroads.org.hk/browse/GCW-531
> fetch messages if missing in data-store on tapping notification

- app/components/loading.js
- app/controllers/subscriptions.js
- app/models/offer.js
- Ember update from 2.8 to 2.9
- Bug fix on error screen overlay
> Latest updates for live release

- app/components/phone-number.js
- app/controllers/subscriptions.js
- app/models/offer.js
- app/routes/application.js
- app/services/logger.js
- app/services/messages.js
- public/winstore-jscompat.js
> Fix code climate issue

- app/components/init-foundation.js
Reverts crossroads/shared.goodcity#198
> Revert "GCW-1826 Disable off canvas scroll"

- app/routes/application.js
Hi Team,
This PR is for ticket: https://jira.crossroads.org.hk/browse/GCW-1862
Please review and let me know if any changes are required.
Thanks.
> pics and terms-condition path added in Unauthenticated method

- app/controllers/authenticate.js
- app/services/app-review.js
Hi Team,
This PR contains changes for : 
- Add unauthorised pop-up if user is not allowed to login into app.
- Add AppReview Service. (GCW-1920)
Please review and let me know if any changes required.
Thanks.
> #JuneRelease1

- addon/controllers/offer/transport_details.js
- addon/locales/en/translations.coffee
- addon/locales/zh-tw/translations.coffee
Hi,
This is PR for issue GCW-2056- Donor: Transport detail cancel cancel bug.
https://jira.crossroads.org.hk/browse/GCW-2056.
I have changed the text of the button and new text has been added in translation file.
Please review it and let me know if any change is required.
Thanks
> cancel button text changed to cancel transport

- app/controllers/item/edit_images.js
I think this whole class probably needs refactoring as it's very confusing. I went for minimal changes since Matt doesn't want to spend a lot of effort on this task.
The idea here is that clicking on "Add item" on a browser, doesn't show the file explorer. Instead we go to the item details page, and then we can upload an image from there !!!!
> GCW-2188 On donor app (browser only), we can create items without an image

- app/controllers/notifications.js
Hi Team,
This PR fixes Admin: something went wrong after submitting an appointment on Browse
Jira ticket:- https://jira.crossroads.org.hk/browse/GCW-2387
Please review
> GCW-2387 Don't show order notification to Donor and Admin app

- app/controllers/application.js
- app/styles/_shared_app.scss
- app/styles/_smart_banner.scss
- app/templates/application.hbs
- bower.json
- package.json
- yarn.lock
Hi Team,
This is PR for JIRA ticket GCW-1929- Add "download/open App" banner to web versions of each app.
I have added this change in this repo which will reflect the change for both DONOR and ADMIN app.
Please review the PR and let me know if any change is required.
Thanks.
> GCW-1929 download banner for web

- app/templates/application.hbs
Hi Team,
This PR is for restricting Banner inside mobile app. Please review the PR and let me know.
Thanks
> Fix: banner condition for mobile app added

- app/styles/_smart_banner.scss
- app/templates/application.hbs
Hi Team,
This PR is regarding pushing the content below banner. Please review the PR and let me know if any change is required.
Thanks
> FIX: Pushing body content below banner.

- app/controllers/application.js
Hi Team,
This PR is for JIRA ticket GCW-2226-Donor: Change "Support GoodCity" & remove Braintree. Braintree has been removed and redirected to crossroads website.
Please review the PR and let me know if any change is required. 
Thanks.
> GCW-2226- Removal of Braintree and redirect user to Goodcity website.

- app/mixins/preload_data.js
Since we're loading a lot less data in the admin app now, we're manually fetching the records that we need to populate the UI. More of these will probable come later
Note: will merge asap for testing
> Load unread messages for Admin app

- addon/controllers/messages_base.js
- app/mixins/preload_data.js
- app/models/image.js
- app/models/message.js
- app/models/offer.js
- app/services/cloudinary-utils.js
- app/services/messages.js
- package.json
- tests/unit/model/image-test.js
- tests/unit/model/offer-test.js
To make the payload smaller AND support PES, a display image cloudinary id for the offer is now added to the record
> Support offer.display_image_cloudinary_id

- app/services/cordova.js
Hi Team,
This PR migrates gcm to fcm.
Please review.
Thanks.
> migrate gcm to fcm

- app/mixins/preload_data.js
- app/routes/post_login.js
Hi Team, 
This PR is for redirecting Admin User to dashboard instead of `my_list` page. Please review the PR.
Thanks.
> GCW- 2473- Replace Admin Offers UI with Dashboard and Search Filters

- app/routes/post_login.js
Reverts crossroads/shared.goodcity#245
> Revert "GCW- 2473- Replace Admin Offers UI with Dashboard and Search Filters"

- app/routes/post_login.js
Reverts crossroads/shared.goodcity#247
> Revert "Revert "GCW- 2473- Replace Admin Offers UI with Dashboard and Search Filters""

- addon/controllers/messages_base.js
- addon/routes/messages_base.js
- app/controllers/subscriptions.js
- app/mixins/preload_data.js
- app/services/messages.js
- app/utils/ajax-promise.js
This PR makes more sense if you review https://github.com/crossroads/api.goodcity/pull/801 first.
This is the front-end implementations of those api changes
> Paginated messages

- app/services/messages.js
Quick fix - nothing critical but the wrong number was showing
Will add tests tomorrow but pushing for release ASAP
> Only increment message unread count if the message is unread

- addon/controllers/messages_base.js
- addon/routes/messages_base.js
> Only mark as read if conversation is active on screen

- app/components/online-button.js
- app/models/company.js
- app/models/offer.js
- app/models/user.js
- app/routes/application.js
- app/templates/message_template.hbs
- tests/unit/model/offer-test.js
Hi Team,
This PR contains corporate donor feature related changes.
Please review.
Thanks.
> Gcw 2691 coprporate donor

- app/controllers/item/edit_images.js
Hi Team,
This PR is for ticket GCW-2697-Allow create/inventorying of an item in one step. It has changes related to adding item and inventorying it one step. Please review the PR and let me know if any change is required.
> GCW- 2697- Allow create/inventorying of an item in one step

- app/templates/delivery/book_timeslot.hbs
- app/templates/delivery/book_van.hbs
- app/templates/delivery/drop_off_schedule.hbs
- app/templates/offer/plan_delivery.hbs
`tagName` added for `online-buttons`. Please review this PR.
> GCW-2770-Admin: It's not possible to book transport with Gogovan or to Crossroads for reviewed items.

- app/routes/application.js
Render error messages coming from the API.
> Gcw 2763 handle errors graciously

- app/services/cordova.js
Hi Team,
This PR is regarding adding Push Notification permission check for iOS for donor app. Please, review this PR and let me know if any change is required.
Thanks
> FIX=> Donor iOS push notification permission fix

- app/models/printer.js
Hi Team,
This PR add printer model.
Please review.
Thanks.
> add printer model

- app/controllers/item/edit_images.js
Ticket: https://jira.crossroads.org.hk/browse/GCW-2761
This PR fixes issue with the deletion of last image for an item in an offer.
> GCW-2761 fixed issue with deletion of last-image

- app/controllers/item/edit_images.js
This PR fixes 
- https://jira.crossroads.org.hk/browse/GCW-2644
> GCW-2644 Fix item duplication not creating new item

- app/models/image.js
As titled. Required for Admin changes
> Add imageable_type/imageable_id to image model

- addon/locales/en/translations.coffee
- addon/locales/zh-tw/translations.coffee
###Ticket Link
https://jira.crossroads.org.hk/browse/GCW-2408
###What PR do?
Change of text from not really to not now
> GCW-2408-Change of text from not really to not now

- app/styles/templates/_message_template.scss
###Ticket Number:
https://jira.crossroads.org.hk/browse/GCW-2696
###What does the PR : 
Fixes Issue of textbox in mobile apps
###Screenshot:
> GCW-2696-UI fix for textbox in message section

- app/components/numeric-input.js
###Ticket Link:
https://jira.crossroads.org.hk/browse/GCW-2253
What does this PR do?
Non-numerical Values cannot be copied
> GCW-2253 Non numericals values now cannot be copied

- app/models/offer.js
https://jira.crossroads.org.hk/browse/GCW-3285
FEATURE: This PR adds feature to reopen closed/cancelled offers.
> GCW-3285- Add a 'reopen' button to the offer details page

- app/models/offer.js
https://jira.crossroads.org.hk/browse/GCW-3285
This PR adds computed property to detect offer in "Received" state.
> add computed property for showing resume-receiving

- app/controllers/delivery/address_details.js
- app/templates/delivery/address_details.hbs
https://jira.crossroads.org.hk/browse/GCW-2483
The only change is in the action `onTerritoryChange` 😅
> Editing the Transport collection address region isn't working

- app/services/messages.js
This PR fixes an error popup on notification, which was occurring due to calling `.get` on plain JSON message payload.
> GCW-3412-Admin: Error message when notification deep link is selected

- app/adapters/application.js
- app/routes/application.js
- app/utils/polyfill.js
Lodash is not supported in Donor App because of old Ember version
This PR will create a polyfill method for _.get
> Remove lodash

- app/controllers/subscriptions.js
Adds the ability to handle custom types from the source app, without ever modifying this (unmanageable) file.
> ADD: Support for custom subscription handlers

- app/routes/application.js
- app/services/logger.js
> GCW-3288 FIX: infinite reload on ios 13

- app/controllers/application.js
- app/templates/application.hbs
This PR adds a global component partial in `application.hbs`.
> GCW-3508-Default message UI

- app/services/messages.js
Ticket Link:
https://jira.crossroads.org.hk/browse/GCW-3588
What does this PR do?
Marks all unread notifications as read in admin app
> GCW-3588 - Resolve issue marking all notifications as read does not work in Admin

- app/controllers/offer/plan_delivery.js
Fixes the error of Attempted to handle event `willCommit` on while in state root.empty , added a state check to prevent that
https://github.com/crossroads/shared.goodcity/pull/312/files#diff-2d38b71eae65369509fed871c988682fab6aadd3d8b5ddf09e78a676519618d6R62
> GCW-3636 Fix delivery model state issue for transport bookings

- addon/locales/en/translations.coffee
- addon/locales/zh-tw/translations.coffee
- app/controllers/authenticate.js
- app/styles/templates/_index.scss
- app/templates/authenticate.hbs
- app/templates/login.hbs
Ticket Link:
https://jira.crossroads.org.hk/browse/GCW-3649
What does this PR do?
Adds timer for otp resending
> GCW-3649 Add timer to otp resend pin

- app/models/message.js
- app/services/message-link-convertor.js
> Update feedback form url

- addon/locales/zh-tw/translations.coffee
https://jira.crossroads.org.hk/browse/GCW-3720
> Updating translations

- app/controllers/item/edit_images.js
https://github.com/crossroads/app.goodcity/issues/408
This PR reduces image size by adding properties like `targetHeight`, `targetWidth`, and `quality`.
Please review this PR and let me know if anything else is required.
> Issue-408 Reduce camera image upload file size(for donor & admin app)
